using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TechSquad.Models.Models;
using TechSquad.Models.ViewModels;
using TechSquad.Services.IServices;

namespace TechSquad.Application.Controllers
{
    public class AdminController : Controller
    {
        private readonly IUserManagerService _userManagerService;
        private readonly IMapper _mapper;
        private readonly IToastNotification _toastNotification;
        private readonly UserManager<ApplicationUser> _userManager;
        public AdminController(IUserManagerService userManagerService, IMapper mapper, IToastNotification toastNotification, UserManager<ApplicationUser> userManager)
        {
            _userManagerService = userManagerService;
            _mapper = mapper;
            _toastNotification = toastNotification;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View("AdminDashboard");
        }

        #region User Settings
        public IActionResult GetAllUser()
        {
            //var res = _userManagerService.GetAllUser();
            List<ApplicationUser> user  = _userManager.Users.ToList();
            return View("UserList", user );
        }

        [HttpGet]
        public IActionResult AddUser()
        {
            return View(new ApplicationUser());
        }

        [HttpPost]
        public async Task<IActionResult> AddUserAsync(ApplicationUser model)
        {
            //var res = _mapper.Map<AspNetUser>(model);
            //Add AutoGenerated Password
            RandomNumberGenerator obj = new RandomNumberGenerator();
            var Password = obj.RandomPassword();
            var status = await _userManager.CreateAsync(model, Password);
            if (status != null)
            {
                _toastNotification.AddSuccessToastMessage("User Added Successfully.password is :"+Password);
            }
            else
            {
                _toastNotification.AddErrorToastMessage("Some Error Occured");
            }
            return View("UserList");
        }

        [HttpGet]
        public async Task<IActionResult> EditUserAsync(string id)
        {
            ApplicationUser user = await _userManager.FindByIdAsync(id);
           // var res = _mapper.Map<UserViewModel>(user);
            return View("AddUser",user);
        }

        //public IActionResult DeleteUser(int id)
        //{
        //    var status = _userManager.del
        //    if (status)
        //    {
        //        _toastNotification.AddSuccessToastMessage("User Deleted Successfully");
        //    }
        //    else
        //    {
        //        _toastNotification.AddErrorToastMessage("Some Error Occured");
        //    }
        //    return View("UserList");
        //}

        #endregion

    }
}
